### ISSUE TITLE
TypeScript error when using reeffect with other effector libraries

### ISSUE THREAD

**Issue by MihailKolesnikov** [yumauri/effector-reeffect#11]
TypeScript gives error when i use reeffect with [patronum/pending](https://github.com/effector/patronum/tree/main/pending)

![image](https://user-images.githubusercontent.com/70065394/94166982-a5e3b500-fe94-11ea-9bcb-b8972bb3c0f8.png)

**Comment by yumauri** [comment]
Alas, will not be fixed due to #26, I suggest you to remove `effector-reeffect` from your codebase as soon as possible.

Thank you for being this package user, but we need to go further.
